server:
  port: 1111
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/