# mybatis
# 对应实体类的包名
mybatis:
  typeAliasesPackage: com.example.dto
# mapper.xml文件所在位置，我放到了resources下面
  mapper-locations: classpath:**/mapper/*.xml
logging:
  level:
     com.example.dao : debug
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 0
    pool:
      maxIdle: 100
      minIdle: 5
      maxActive: 2000
      maxWait: -1
  profiles:
    active: peer
  datasource:
  # 使用druid数据源
    #type: com.alibaba.druid.pool.DruidDataSource
    dniver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create #第一次简表 create 后面用 update
    show-sql: true
#java -jar demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2
#java -jar server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2