server:
  port: 1111
spring:
  application:
    name: eureka-server
  profiles:
    include: config-server
eureka:
  instance:
    hostname: peer1
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      register-with-eureka: false
      fetch-registry: false
      defaultZone: http://peer1:1111/eureka/
